## Modulo Numpy en python para computacion numerica

* [Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/)
* [Linear algebra explained in four pages](http://www.souravsengupta.com/cds2016/lectures/Savov_Notes.pdf)
* [Calculus for DL ](http://tutorial.math.lamar.edu/pdf/Calculus_Cheat_Sheet_All.pdf)
* [Estadistica para DL ](http://web.mit.edu/~csvoss/Public/usabo/stats_handout.pdf)
* [Probability Cheatsheet](https://static1.squarespace.com/static/54bf3241e4b0f0d81bf7ff36/t/55e9494fe4b011aed10e48e5/1441352015658/probability_cheatsheet.pdf)
* [Awesome Math](https://github.com/llSourcell/learn_math_fast)


In [ ]:
import numpy as np

In [ ]:
numeros=[1,2,3,4,5]
a= np.array(numeros)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
lista2=np.random.randn(3,3)
print(lista2)

[[ 0.37943179 -0.29195755  0.32873426]
 [-0.1664602   0.73593126  0.62639475]
 [ 1.42114253 -0.80675132  0.93477066]]


In [ ]:
# matriz

matriz =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matriz.shape

(3, 3)

#### Intalar modulos en python
! pip install numpy

In [ ]:
matriz[0,:]

array([1, 2, 3])

In [ ]:
matriz[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
zeros=np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
unos=np.ones((3,3))
print(unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
sietes=np.full((3,3),7)
print(sietes)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
otro_siete=unos*7
print(otro_siete)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
aleatorio=np.random.random((2,2))
print(aleatorio)

[[0.02305581 0.38349154]
 [0.99791115 0.25508945]]


In [ ]:
arreglo=np.array([[1,2],[3,4],[5,6]],dtype=np.int64)
arreglo>5

array([[False, False],
       [False, False],
       [False,  True]])

In [ ]:
arreglo[arreglo>5]

array([6], dtype=int64)

In [ ]:
arreglo.dtype

dtype('int32')

### Operaciones matematicas con numpy
 

In [ ]:
x=np.array([[1,1],[1,1]])
y=np.array([[2,2],[2,2]])

print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


Producto punto

(nxm) * (mxn) ==(nxn)

In [ ]:
producto_punto=x.dot(y)
print(producto_punto)

[[4 4]
 [4 4]]


In [ ]:
dot_prod= x @ y
print(dot_prod)

[[4 4]
 [4 4]]


#### Broadcasting 
podemos multiplicar un vector de nxm dimensiones por uno  de forma nx1 o 1xm

In [ ]:
vector_1D=np.array([[5]])
matriz00=dot_prod*vector_1D
print(vector_1D.shape)
print(matriz00)

(1, 1)
[[20 20]
 [20 20]]


In [ ]:
suma_vec=dot_prod + vector_1D
print(suma_vec)

[[9 9]
 [9 9]]


#### Operaciones estadisticas

In [ ]:
z=np.array([[11,12],[21,22]])

print(np.sum(z))

66


In [ ]:
# Sumar renglones, axis =0 son suma de renglones y axis=1 suma de columnas
print(np.sum(z,axis=1))

[23 43]


#### Element wise product

In [ ]:
vec1=np.random.randn(8)
vec2=np.random.randn(8)*10


In [ ]:
element_wise=vec1*vec2
element_wise

array([-4.88021752,  0.10843468,  0.45505892, -7.26050455,  4.9703986 ,
       32.50072103,  3.14289181,  0.78959283])

In [ ]:
# maximo numeroi de dos vectores
maximo_vec=np.maximum(vec1,vec2)
print(maximo_vec)

[ 7.0068606   1.19106941  1.76788277  7.74606204  7.62911055 16.11790472
  6.86709031 -0.37736609]


Pedir ayuda a pyhton

In [ ]:
help(np.maximum)

Help on ufunc object:

maximum = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arr

#### Reshape arrays o cambio de dimensiones de arreglos matriciales

In [ ]:
arr= np.arange(20)
print(arr.shape)

(20,)


In [ ]:
# cambiar la dimension del vector a una matrix para operaciones numericas 
arr1_cambiado=arr.reshape((4,5))


In [ ]:
arr1_cambiado.shape

(4, 5)

#### Transpuesta de una matriz 

In [ ]:
print(arr1_cambiado.T.shape)

(5, 4)


#### Numeros aleatorios 

In [ ]:
# Distribucion normal aleatoria 
Z = np.random.normal(size=(1,5))
Z

array([[-0.34431217,  1.46214798,  0.72679601,  0.40674623,  1.08124449]])

In [ ]:
# numeros aleatorio enteros
Y =np.random.randint(low=2,high=50,size=4)
Y

array([ 2, 39, 10, 28])

In [ ]:
# Desviacion estandar
std=np.std(Z)
print(std)

0.616103492100889


In [ ]:
# media 
np.mean(Z)


0.6665245094223933

In [ ]:
# mediana
np.median(Z)

0.7267960083911319

### Concatenacion y union de matrices (Merge data sets) 

In [ ]:
K =np.random.randint(low=2,high=50,size=(2,2))
print(K)

[[44 47]
 [36 27]]


In [ ]:
M =np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[27 16]
 [29 11]]


In [ ]:
# concatenacion vertical
np.vstack((K,M))

array([[44, 47],
       [36, 27],
       [27, 16],
       [29, 11]])

In [ ]:
# concatenacion horizontal
np.hstack((K,M))

array([[44, 47, 27, 16],
       [36, 27, 29, 11]])

In [ ]:
np.concatenate([K, M.T],axis=1) # Eliges el axis para laconcatenacion

array([[44, 47, 27, 29],
       [36, 27, 16, 11]])

In [ ]:
np.max(K)

47

In [ ]:
np.min(K)

27

In [ ]:
np.argmin(K)

3